import React from 'react';
import {scaleLinear, ScaleLinear} from 'd3-scale';

import constants from './constants';

export interface UseMinPrevScaleArgs {
  /** Height of the SVG canvas. */
  height: number;
  /** Domain for the prevalence scale. */
  minPrevalenceDomain: [number, number];
}

/**
 * Construct a linear scale for minimum prevalence values.
 *
 * @param args - {@link UseMinPrevScaleArgs} with geometry and domain.
 * @returns Scale mapping prevalence to y positions.
 */
  export function useMinPrevalenceScale({
    height,
    minPrevalenceDomain
  }: UseMinPrevScaleArgs): ScaleLinear<number, number> {
  const axisStart = (
    height -
    constants.paddingV -
    constants.axisTitleFontSize -
    2 * constants.axisTitlePadding -
    constants.xAxisLabelHeight -
    constants.axisTickSize
  );
  const axisEnd = constants.paddingV;
  return React.useMemo(
    () =>
      scaleLinear()
        .domain(minPrevalenceDomain)
        .range([axisStart, axisEnd]),
    [axisEnd, axisStart, minPrevalenceDomain]
  );
}

interface UseAxisPathDataArgs {
  scale: ScaleLinear<number, number>;
  axisLeft: number;
  ticks: number[];
}

  function useAxisPathData({
    scale,
    axisLeft,
    ticks
  }: UseAxisPathDataArgs): string {
  return React.useMemo(
    () => {
      const [y1, y2] = scale.range();
      const [start, end] = scale.domain();
      const {axisTickSize} = constants;

      const pathData = [
        `M ${axisLeft - axisTickSize} ${y1}`,
        `h ${axisTickSize}`,
        `v ${y2 - y1}`,
        `h ${- axisTickSize}`
      ];

      for (const tick of ticks) {
        if (tick === start || tick === end) {
          continue;
        }
        const tickY = scale(tick);
        pathData.push(`M ${axisLeft} ${tickY}`);
        pathData.push(`h ${- axisTickSize}`);
      }

      return pathData.join(' ');
    },
    [axisLeft, scale, ticks]
  );
}

function pcntFormat(value: number): string {
  return `${(value * 100).toFixed(0)}%`;
}

  export interface MinPrevalenceAxisProps {
    /** Scale generated by {@link useMinPrevalenceScale}. */
    scale: ScaleLinear<number, number>;
    /** Tick values to display along the axis. */
    ticks: number[];
  }

/**
 * Render the left axis displaying mutation detection thresholds.
 *
 * @param props - {@link MinPrevalenceAxisProps} defining scale and ticks.
 * @returns SVG group for the left axis.
 */
export default function MinPrevalenceAxis({
  scale,
  ticks
}: MinPrevalenceAxisProps): JSX.Element {
  const axisLeft = (
    constants.paddingH +
    constants.axisTitleFontSize +
    2 * constants.axisTitlePadding +
    constants.yAxisLabelWidth +
    constants.axisTickSize +
    constants.yAxisOffsetH
  );

  const pathData = useAxisPathData({
    scale,
    axisLeft,
    ticks
  });
  return (
    <g>
      <path
       d={pathData}
       fill="none"
       stroke="#000"
       strokeWidth={constants.strokeWidth}
      />
      {ticks.map(tick => (
        <text
         key={`tick-label-${tick}`}
         x={axisLeft - constants.axisTickSize - constants.axisLabelFontSize / 3}
         y={scale(tick) + constants.axisLabelFontSize / 3}
         fontSize={constants.axisLabelFontSize}
         fill="#000"
         textAnchor="end">
          {pcntFormat(tick)}
        </text>
      ))}
      <text
       writingMode="vertical-rl"
       transform="rotate(-180)"
       x={- constants.paddingH}
         y={- scale.range().reduce((a: number, b: number) => a + b, 0) / 2}
       fontSize={constants.axisTitleFontSize}
       fill="#000"
       textAnchor="middle">
        Mut detection threshold
      </text>
    </g>
  );
}
