import React from 'react';
import PropTypes from 'prop-types';

import {scaleLog} from 'd3-scale';
import React from 'react';
import {scaleLog} from 'd3-scale';

import constants from './constants';

export interface UseMixtureRateScaleArgs {
  /** Width of the SVG canvas. */
  width: number;
  /** Tick values displayed on the axis. */
  mixtureRateTicks: number[];
}

/**
 * Build a logarithmic scale for mixture rate values.
 *
 * @param args - {@link UseMixtureRateScaleArgs} containing width and ticks.
 * @returns Scaling function mapping mixture rates to x positions.
 */
export function useMixtureRateScale({
  width,
  mixtureRateTicks
}: UseMixtureRateScaleArgs) {
  const axisStart = (
    constants.paddingH +
    constants.axisTitleFontSize +
    2 * constants.axisTitlePadding +
    constants.yAxisLabelWidth +
    constants.axisTickSize
  );
  const axisEnd = width - constants.paddingH;
  return React.useMemo(
    () => {
      const mixtureRateDomain = [
        Math.min(...mixtureRateTicks),
        Math.max(...mixtureRateTicks)
      ];
      const nonZeroMinTick = Math.min(...mixtureRateTicks.filter(n => n > 0));
      const level = 0.2 * 10 ** -Math.floor(Math.log10(nonZeroMinTick));

      const baseScale = scaleLog()
        .base(10)
        .domain(mixtureRateDomain.map(n => n * level + 1))
        .range([axisStart, axisEnd]);
      const scale = value => baseScale(value * level + 1);
      scale.domain = () => baseScale.domain().map(n => (n - 1) / level);
      scale.range = baseScale.range;
      return scale;
    },
    [axisStart, axisEnd, mixtureRateTicks]
  );
}

interface UseAxisPathDataArgs {
  scale: (v: number) => any;
  axisTop: number;
  ticks: number[];
}

function useAxisPathData({
  scale,
  axisTop,
  ticks
}: UseAxisPathDataArgs) {
  return React.useMemo(
    () => {
      const [x1, x2] = scale.range();
      const [start, end] = scale.domain();
      const {axisTickSize} = constants;

      const pathData = [
        `M ${x1} ${axisTop + axisTickSize}`,
        `v ${-axisTickSize}`,
        `h ${x2 - x1}`,
        `v ${axisTickSize}`
      ];

      for (const tick of ticks) {
        if (tick === start || tick === end) {
          continue;
        }
        const tickX = scale(tick);
        pathData.push(`M ${tickX} ${axisTop}`);
        pathData.push(`v ${axisTickSize}`);
      }

      return pathData.join(' ');
    },
    [axisTop, scale, ticks]
  );
}

function pcntFormat(value: number): string {
  if (value < 0.1) {
    return `${(value * 100).toPrecision(1)}%`;
  } else {
    return `${(value * 100).toFixed(0)}%`;
  }
}

export interface MixtureRateAxisProps {
  /** Scale generated by {@link useMixtureRateScale}. */
  scale: (v: number) => number;
  /** Height of the SVG canvas. */
  height: number;
  /** Tick values to label on the axis. */
  ticks: number[];
}

/**
 * Render the bottom axis displaying nucleotide mixture rate ticks.
 *
 * @param props - {@link MixtureRateAxisProps} defining scale and geometry.
 * @returns SVG group containing axis line and labels.
 */
export default function MixtureRateAxis({
  scale,
  height,
  ticks
}: MixtureRateAxisProps): JSX.Element {
  const axisTop = (
    height -
    constants.paddingV -
    constants.axisTitleFontSize -
    2 * constants.axisTitlePadding -
    constants.xAxisLabelHeight -
    constants.axisTickSize +
    constants.xAxisOffsetV
  );

  const pathData = useAxisPathData({
    scale,
    axisTop,
    ticks
  });
  return (
    <g>
      <path
       d={pathData}
       fill="none"
       stroke="#000"
       strokeWidth={constants.strokeWidth}
      />
      {ticks.map(tick => (
        <text
         key={`tick-label-${tick}`}
         x={scale(tick)}
         y={axisTop + constants.axisTickSize + constants.axisLabelFontSize}
         fontSize={constants.axisLabelFontSize}
         fill="#000"
         textAnchor="middle">
          {pcntFormat(tick)}
        </text>
      ))}
      <text
       x={scale.range().reduce((a, b) => a + b, 0) / 2}
       y={height - constants.paddingV}
       fontSize={constants.axisTitleFontSize}
       fill="#000"
       textAnchor="middle">
        Nucleotide mixture threshold
      </text>
    </g>
  );
}
